# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MacroClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JYMacros', path: "./../.."
  pod 'ModuleA', path: "./../ModuleA"
#  pod 'JYMacros', git: "https://github.com/SSBun/demo_swift_macro_pod.git", tag: '0.0.8'

end
